name: Publish jFaaS:jFaaS:x.y.z to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the JAR to publish (e.g., 1.0.0, 1.0.1, etc.)'
        required: true
        default: '1.0-SNAPSHOT' # Optional, you can set a default version if you want

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: github # This must match the server ID in your settings.xml
          settings-path: ${{ github.workspace }} # This will be used to read the settings.xml

      - name: Create jar file
        run: ./gradlew install && ./gradlew shadowJar

      - name: Deploy JAR to GitHub Packages
        run: |
          mvn deploy:deploy-file \
            -Dfile=./build/libs/jFaaS-all.jar \
            -DgroupId=jFaaS \
            -DartifactId=jFaaS \
            -Dversion=${{ github.event.inputs.version }} \
            -Dpackaging=jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/sashkoristov/jFaaS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
