name: Publish jFaaS:jFaaS:x.y.z to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the JAR to publish (e.g., 1.0.0, 1.0.1, etc.)'
        required: true
        default: '1.0-SNAPSHOT' # Optional, you can set a default version if you want

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: 
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish to GitHub Packages
        run: ./gradlew -Pversion=${{ github.event.inputs.version }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
